#!/bin/bash

# adapt config
sudo /usr/bin/adapt-config.sh ${DOCKER_CORES}

# if /data/hadoop exists --> no namenode format needed
if [ ! -d "/data/hadoop" ]; then
	echo "No HDFS folder in data folder. Format Namenode..."
	mkdir /data/hadoop
	chmod 1777 /data/hadoop
  sudo -u hdfs hdfs namenode -format
else
	echo "Found HDFS folder in data folder. Reuse /data/hadoop."
fi

# start HDFS
for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do sudo service $x start ; done

# delete cache directory in HDFS
su -s /bin/bash hdfs -c '/usr/bin/hadoop fs -rmr /var/lib/hadoop-hdfs/cache/mapred/mapred/staging'

sudo /usr/bin/init-hdfs.sh

# add home dir for root
sudo -u hdfs hadoop fs -mkdir -p /user/root
sudo -u hdfs hadoop fs -chown root /user/root

# start Jobtracker and Tasktracker
for x in `cd /etc/init.d ; ls hadoop-0.20-mapreduce-*` ; do sudo service $x start ; done

#print ip
hostname=$(grep "$HOSTNAME" /etc/hosts|awk '{print $1}')
echo "Congratulations! Cluster is running on $hostname"

# end with command line if BASH command is set
if [ ${EXEC_BASH} == "true" ]
then
	/bin/bash
fi
